apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/lucarval-tenant/devfile-sample-java-springboot-basic/devfile-sample-java-springboot-basic@sha256:60c05d076b6ef847a3429c190bd3427832ec4a8ec03b696c3f9b559d19db6b6a
        name: my-java-springboot
        resources: {}
status: {}
